# Generated by Django 2.2.5 on 2020-06-12 20:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200613_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2020, 6, 12, 20, 49, 5, 851981, tzinfo=utc)),
        ),
    ]
