# Generated by Django 2.2.5 on 2020-06-12 21:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200613_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='deadline',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='student',
            name='work_to_do',
            field=models.TextField(max_length=1000, verbose_name='Assign Some Work'),
        ),
    ]
